### ISSUE TITLE
gamerappa Likes new bluey nsfw

### ISSUE THREAD

**Issue by cleber299** [cheeserox/cheeserox-old#135]
![image](https://user-images.githubusercontent.com/101748005/158676321-29e354b5-4fc3-42a3-b1a8-c165355ef75a.png)

That's not a diaper in uncropped, that's a DICK!

new fetish detected... :scream:

**Comment by jkrosado** [comment]
> new fetish detected... 😱

he used to be like this pre-bluey

**Comment by cleber299** [comment]
> > new fetish detected... 😱
> 
> he used to be like this pre-bluey

don't think gamepedo was into this weird furry collar thing (bdsm???)
